# Function to create tool files
function New-CreateToolFiles {
    param (
        [Parameter(Mandatory=$True)] [array]$ToolDefinitions,
        [Parameter(Mandatory=$True)] [string]$Source
    )

    if (Test-Path -Path "C:\Users\WDAGUtilityAccount\Documents\tools\wscommon.ps1") {
        $BASE_PATH = "C:\log\"
    } else {
        $BASE_PATH = ".\downloads"
    }

    if (! (Test-Path -Path "$BASE_PATH\dfirws")) {
        New-Item -ItemType Directory -Force -Path "$BASE_PATH\dfirws" | Out-Null
    }

    # Remove old helper files for HTTP installations and create new ones.
    if (Test-Path -Path "$BASE_PATH\dfirws\verify_${source}.ps1") {
        Remove-Item -Force "$BASE_PATH\dfirws\verify_${source}.ps1" | Out-Null 2>&1
    }
    Set-Content -Path "$BASE_PATH\dfirws\verify_${source}.ps1" -Value "# verify_${source}.ps1`n# This file is autogenerated during setup. Do not edit manually.`n"

    if (Test-Path -Path "$BASE_PATH\dfirws\install_${source}.ps1") {
        Remove-Item -Force "$BASE_PATH\dfirws\install_${source}.ps1" | Out-Null 2>&1
    }
    Set-Content -Path "$BASE_PATH\dfirws\install_${source}.ps1" -Value "# install_${source}.ps1`n# This file is autogenerated during setup. Do not edit manually.`n"

    if (Test-Path -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1") {
        Remove-Item -Force "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" | Out-Null 2>&1
    }
    Set-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "# dfirws_folder_${source}.ps1`n# This file is autogenerated during setup. Do not edit manually.`n"

    # Iterate over $ToolDefinitions to create helper files for HTTP installations.
    for ($i = 0; $i -lt $ToolDefinitions.Count; $i++) {
        # Create helper file verify_${source}.ps1 called from verify.ps1.
        # Use $ToolDefinitions from this script.

        foreach ($test in $ToolDefinitions[$i].Verify) {
            $verify_type = $test.Type
            $verify_name = $test.Name
            $verify_expect = $test.Expect 

            if ("command" -eq $verify_type) {
                Add-Content -Path "$BASE_PATH\dfirws\verify_${source}.ps1" -Value "Test-Command `"$verify_name`" `"$verify_expect`""
            }
        }

        # Create helper file install_${source}.ps1 called from install_all.ps1.
        # Use $ToolDefinitions from this script.
        $install_verify_command = $ToolDefinitions[$i].InstallVerifyCommand

        if ($null -ne $install_verify_command -and $install_verify_command -ne "") {
            Add-Content -Path "$BASE_PATH\dfirws\install_${source}.ps1" -Value "$install_verify_command"
        }

        # Create helper file dfirws_folder_${source}.ps1 called from dfirws-install.ps1.
        # Use $ToolDefinitions from this script.
        foreach ($link in $ToolDefinitions[$i].Shortcuts) {
            $lnk = $link.Lnk
            $target = $link.Target
            $args = $link.Args
            $icon = $link.Icon
            $workdir = $link.WorkDir

            if ($null -eq $icon) {
                if ($null -eq $args) {
                    Add-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "Add-Shortcut -SourceLnk `"$lnk`" -DestinationPath `"$target`" -WorkingDirectory `"$workdir`""
                } else {
                    Add-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "Add-Shortcut -SourceLnk `"$lnk`" -DestinationPath `"$target`" -Arguments `"$args`" -WorkingDirectory `"$workdir`""
                }
            } else {
                if ($null -eq $args) {
                    Add-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "Add-Shortcut -SourceLnk `"$lnk`" -DestinationPath `"$target`" -IconLocation `"$icon`" -WorkingDirectory `"$workdir`""
                } else {
                    Add-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "Add-Shortcut -SourceLnk `"$lnk`" -DestinationPath `"$target`" -Arguments `"$args`" -IconLocation `"$icon`" -WorkingDirectory `"$workdir`""
                }
            }
        }
    }

    # Export tool metadata for documentation generation.
    $tools_export = @()
    for ($i = 0; $i -lt $ToolDefinitions.Count; $i++) {
        $tool = $ToolDefinitions[$i]
        $category_path = $null

        if ($null -ne $tool.Shortcuts -and $tool.Shortcuts.Count -gt 0) {
            $lnk = $tool.Shortcuts[0].Lnk
            if ($null -ne $lnk) {
                $category_match = [regex]::Match($lnk, "\\Desktop\\dfirws\\(.+)\\[^\\]+$")
                if ($category_match.Success) {
                    $category_path = $category_match.Groups[1].Value
                }
            }
        }

        $category = "Uncategorized"
        if ($null -ne $category_path -and $category_path -ne "") {
            $category = ($category_path -split "\\")[0]
        }

        $tools_export += [ordered]@{
            Name                 = $tool.Name
            Homepage             = $tool.Homepage
            Vendor               = $tool.Vendor
            License              = $tool.License
            LicenseUrl           = $tool.LicenseUrl
            Category             = $category
            CategoryPath         = $category_path
            InstallVerifyCommand = $tool.InstallVerifyCommand
            Shortcuts            = $tool.Shortcuts
            Verify               = $tool.Verify
            Notes                = $tool.Notes
            Tips                 = $tool.Tips
            Usage                = $tool.Usage
            SampleCommands       = $tool.SampleCommands
            SampleFiles          = $tool.SampleFiles
            Tags                 = $tool.Tags
            FileExtensions       = $tool.FileExtensions
            Dependencies         = $tool.Dependencies
            PythonVersion        = $tool.PythonVersion
            SourceType           = $Source
            # Keep a legacy Source field for downstream tools that expect it.
            Source               = $Source
        }
    }

    $tools_doc = [ordered]@{
        GeneratedAt  = (Get-Date).ToString("s")
        SourceScript = "resources/download/${source}.ps1"
        Tools        = $tools_export
    }

    Set-Content -Path "$BASE_PATH\dfirws\tools_${source}.json" -Value ($tools_doc | ConvertTo-Json -Depth 8)
}
