# Function to create tool files
function Normalize-ToolDefinitions {
    param(
        [Parameter(Mandatory=$True)] [array]$ToolDefinitions
    )

    $defaultToolValues = [ordered]@{
        Name                 = ""
        Homepage             = ""
        Vendor               = ""
        License              = ""
        LicenseUrl           = ""
        Category             = ""
        Shortcuts            = @()
        InstallVerifyCommand = ""
        Verify               = @()
        Notes                = ""
        Tips                 = ""
        Usage                = ""
        SampleCommands       = @()
        SampleFiles          = @()
        Tags                 = @()
        FileExtensions       = @()
        Dependencies         = @()
        PythonVersion        = ""
    }

    for ($i = 0; $i -lt $ToolDefinitions.Count; $i++) {
        $tool = $ToolDefinitions[$i]
        foreach ($property in $defaultToolValues.Keys) {
            if (! $tool.ContainsKey($property) -or $null -eq $tool[$property]) {
                $tool[$property] = $defaultToolValues[$property]
            }
        }

        foreach ($shortcut in $tool.Shortcuts) {
            if (! $shortcut.ContainsKey("Lnk") -or $null -eq $shortcut.Lnk) { $shortcut["Lnk"] = "" }
            if (! $shortcut.ContainsKey("Target") -or $null -eq $shortcut.Target) { $shortcut["Target"] = "" }
            if (! $shortcut.ContainsKey("Args") -or $null -eq $shortcut.Args) { $shortcut["Args"] = "" }
            if (! $shortcut.ContainsKey("Icon") -or $null -eq $shortcut.Icon) { $shortcut["Icon"] = "" }
            if (! $shortcut.ContainsKey("WorkDir") -or $null -eq $shortcut.WorkDir) { $shortcut["WorkDir"] = "" }
        }

        foreach ($verify in $tool.Verify) {
            if (! $verify.ContainsKey("Type") -or $null -eq $verify.Type) { $verify["Type"] = "" }
            if (! $verify.ContainsKey("Name") -or $null -eq $verify.Name) { $verify["Name"] = "" }
            if (! $verify.ContainsKey("Expect") -or $null -eq $verify.Expect) { $verify["Expect"] = "" }
        }
    }

    return $ToolDefinitions
}

function New-CreateToolFiles {
    param (
        [Parameter(Mandatory=$True)] [array]$ToolDefinitions,
        [Parameter(Mandatory=$True)] [string]$Source
    )

    if (Test-Path -Path "C:\Users\WDAGUtilityAccount\Documents\tools\wscommon.ps1") {
        $BASE_PATH = "C:\log\"
    } else {
        $BASE_PATH = ".\downloads"
    }

    if (! (Test-Path -Path "$BASE_PATH\dfirws")) {
        New-Item -ItemType Directory -Force -Path "$BASE_PATH\dfirws" | Out-Null
    }

    # Save the full unfiltered list before profile filtering so all tools (with profile
    # metadata) can be exported to the JSON used for documentation generation.
    $AllToolDefinitions = $ToolDefinitions

    # Apply profile filtering to metadata as a safety net so generated verify/install
    # scripts don't reference tools excluded by the active profile.
    if ((Test-Path variable:DFIRWS_EXCLUDE_TOOLS) -and $null -ne $DFIRWS_EXCLUDE_TOOLS -and $DFIRWS_EXCLUDE_TOOLS.Count -gt 0) {
        $filteredToolDefinitions = @()
        foreach ($toolDefinition in $ToolDefinitions) {
            $toolName = "$($toolDefinition.Name)"
            if ((Test-Path variable:DFIRWS_EXTRAS_RESOLVED) -and $null -ne $DFIRWS_EXTRAS_RESOLVED -and $DFIRWS_EXTRAS_RESOLVED -contains $toolName) {
                $filteredToolDefinitions += $toolDefinition
            } elseif ($DFIRWS_EXCLUDE_TOOLS -contains $toolName) {
                continue
            } else {
                $filteredToolDefinitions += $toolDefinition
            }
        }
        $ToolDefinitions = $filteredToolDefinitions
    }

    $ToolDefinitions = Normalize-ToolDefinitions -ToolDefinitions $ToolDefinitions
    # Normalize any tools that were filtered out so they are ready for JSON export too.
    $AllToolDefinitions = Normalize-ToolDefinitions -ToolDefinitions $AllToolDefinitions

    # Remove old helper files for HTTP installations and create new ones.
    if (Test-Path -Path "$BASE_PATH\dfirws\verify_${source}.ps1") {
        Remove-Item -Force "$BASE_PATH\dfirws\verify_${source}.ps1" | Out-Null 2>&1
    }
    Set-Content -Path "$BASE_PATH\dfirws\verify_${source}.ps1" -Value "# verify_${source}.ps1`n# This file is autogenerated during setup. Do not edit manually.`n"

    if (Test-Path -Path "$BASE_PATH\dfirws\install_${source}.ps1") {
        Remove-Item -Force "$BASE_PATH\dfirws\install_${source}.ps1" | Out-Null 2>&1
    }
    Set-Content -Path "$BASE_PATH\dfirws\install_${source}.ps1" -Value "# install_${source}.ps1`n# This file is autogenerated during setup. Do not edit manually.`n"

    if (Test-Path -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1") {
        Remove-Item -Force "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" | Out-Null 2>&1
    }
    Set-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "# dfirws_folder_${source}.ps1`n# This file is autogenerated during setup. Do not edit manually.`n"

    # Iterate over $ToolDefinitions to create helper files for HTTP installations.
    for ($i = 0; $i -lt $ToolDefinitions.Count; $i++) {
        # Create helper file verify_${source}.ps1 called from verify.ps1.
        # Use $ToolDefinitions from this script.

        foreach ($test in $ToolDefinitions[$i].Verify) {
            $verify_type = $test.Type
            $verify_name = $test.Name
            $verify_expect = $test.Expect 

            if ("command" -eq $verify_type) {
                Add-Content -Path "$BASE_PATH\dfirws\verify_${source}.ps1" -Value "Test-Command `"$verify_name`" `"$verify_expect`""
            }
        }

        # Create helper file install_${source}.ps1 called from install_all.ps1.
        # Use $ToolDefinitions from this script.
        $install_verify_command = $ToolDefinitions[$i].InstallVerifyCommand

        if ($null -ne $install_verify_command -and $install_verify_command -ne "") {
            Add-Content -Path "$BASE_PATH\dfirws\install_${source}.ps1" -Value "$install_verify_command"
        }

        # Create helper file dfirws_folder_${source}.ps1 called from dfirws-install.ps1.
        # Use $ToolDefinitions from this script.
        foreach ($link in $ToolDefinitions[$i].Shortcuts) {
            $lnk = $link.Lnk
            $target = $link.Target
            $args = $link.Args
            $icon = $link.Icon
            $workdir = $link.WorkDir

            if ($null -eq $icon) {
                if ($null -eq $args) {
                    Add-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "Add-Shortcut -SourceLnk `"$lnk`" -DestinationPath `"$target`" -WorkingDirectory `"$workdir`""
                } else {
                    Add-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "Add-Shortcut -SourceLnk `"$lnk`" -DestinationPath `"$target`" -Arguments `"$args`" -WorkingDirectory `"$workdir`""
                }
            } else {
                if ($null -eq $args) {
                    Add-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "Add-Shortcut -SourceLnk `"$lnk`" -DestinationPath `"$target`" -IconLocation `"$icon`" -WorkingDirectory `"$workdir`""
                } else {
                    Add-Content -Path "$BASE_PATH\dfirws\dfirws_folder_${source}.ps1" -Value "Add-Shortcut -SourceLnk `"$lnk`" -DestinationPath `"$target`" -Arguments `"$args`" -IconLocation `"$icon`" -WorkingDirectory `"$workdir`""
                }
            }
        }
    }

    # Build a lookup of which named profiles exclude each tool so the documentation
    # generator can show or filter by profile availability.
    # $DFIRWS_PROFILES is populated by local/defaults/profiles.ps1 which is dot-sourced
    # by downloadFiles.ps1 before calling the download sub-scripts.
    $profileExcludeMaps = @{}
    if ((Test-Path variable:DFIRWS_PROFILES) -and $null -ne $DFIRWS_PROFILES) {
        foreach ($profileName in $DFIRWS_PROFILES.Keys) {
            $excludeList = $DFIRWS_PROFILES[$profileName].ExcludeTools
            if ($null -ne $excludeList) {
                $profileExcludeMaps[$profileName] = $excludeList
            }
        }
    }

    # Export tool metadata for documentation generation.
    # Use the unfiltered $AllToolDefinitions so excluded tools are still present in the
    # JSON, annotated with the profiles that include them.  The helper scripts above
    # (verify / install / dfirws_folder) only reference the filtered set.
    $tools_export = @()
    for ($i = 0; $i -lt $AllToolDefinitions.Count; $i++) {
        $tool = $AllToolDefinitions[$i]
        $category_path = $null

        if ($null -ne $tool.Shortcuts -and $tool.Shortcuts.Count -gt 0) {
            $lnk = $tool.Shortcuts[0].Lnk
            if ($null -ne $lnk) {
                $category_match = [regex]::Match($lnk, "\\Desktop\\dfirws\\(.+)\\[^\\]+$")
                if ($category_match.Success) {
                    $category_path = $category_match.Groups[1].Value
                }
            }
        }

        $category = "Uncategorized"
        if ($null -ne $category_path -and $category_path -ne "") {
            $category = ($category_path -split "\\")[0]
        }

        # Determine which profiles include this tool.
        $tool_profiles = [System.Collections.Generic.List[string]]::new()
        $tool_profiles.Add("Full")
        if ($profileExcludeMaps.Count -gt 0) {
            foreach ($profileName in $profileExcludeMaps.Keys) {
                if ($profileName -eq "Full") { continue }
                $excludeList = $profileExcludeMaps[$profileName]
                $isExtra = (Test-Path variable:DFIRWS_EXTRAS_RESOLVED) -and $null -ne $DFIRWS_EXTRAS_RESOLVED -and $DFIRWS_EXTRAS_RESOLVED -contains $tool.Name
                $isExcluded = ($excludeList -contains $tool.Name) -and (-not $isExtra)
                if (-not $isExcluded) {
                    $tool_profiles.Add($profileName)
                }
            }
        } else {
            # profiles.ps1 was not loaded; assume the tool is available in all profiles.
            $tool_profiles.Add("Basic")
        }

        $tools_export += [ordered]@{
            Name                 = $tool.Name
            Homepage             = $tool.Homepage
            Vendor               = $tool.Vendor
            License              = $tool.License
            LicenseUrl           = $tool.LicenseUrl
            Category             = $category
            CategoryPath         = $category_path
            InstallVerifyCommand = $tool.InstallVerifyCommand
            Shortcuts            = $tool.Shortcuts
            Verify               = $tool.Verify
            Notes                = $tool.Notes
            Tips                 = $tool.Tips
            Usage                = $tool.Usage
            SampleCommands       = $tool.SampleCommands
            SampleFiles          = $tool.SampleFiles
            Tags                 = $tool.Tags
            FileExtensions       = $tool.FileExtensions
            Dependencies         = $tool.Dependencies
            PythonVersion        = $tool.PythonVersion
            Profiles             = @($tool_profiles)
            SourceType           = $Source
            # Keep a legacy Source field for downstream tools that expect it.
            Source               = $Source
        }
    }

    $tools_doc = [ordered]@{
        GeneratedAt  = (Get-Date).ToString("s")
        SourceScript = "resources/download/${source}.ps1"
        Tools        = $tools_export
    }

    Set-Content -Path "$BASE_PATH\dfirws\tools_${source}.json" -Value ($tools_doc | ConvertTo-Json -Depth 8)
}
