[project]
site_name = "dfirws tools"
docs_dir = "docs"
site_dir = "site"
extra_css = ["stylesheets/filter.css"]
extra_javascript = ["javascripts/filter.js"]

[project.theme]
name = "material"
features = []
